### ISSUE TITLE
2 bugs found on new Demo (based on Keystone 0.30) : Authentication and Display Blog

### ISSUE THREAD

**Issue by adalidda** [keystonejs/keystone-demo#29]
Hi,

I found 2 issues with the new KeystoneJS Demo:
1. Authentication is not working.
Example: mongodb://user:password@ip:port/databasename?authSource=admin
2. The list of blog is displayed correctly but when I click on the title to display the blog in detail view, I got error 404 Sorry, the page you requested can't be found.

Note: I can use the previous version of demo so the problems are related to the new version.

Thank You
Kosona Chriv

**Comment by jstockwin** [comment]
Closing this because it is so old and we're trying to keep the issue tracker unpolluted. 
Sorry that nobody ever responded to this. 

Your second point is resolved in current master, and authentication works fine, with the slight exception of #59, which has a fix detailed in the comments. 

Please reopen this if you still think it is relevant, or need more help.
