### ISSUE TITLE
Blog post error on post page

### ISSUE THREAD

**Issue by Nosherwan** [keystonejs/keystone-demo#62]
After creating a post from the Admin UI, visit the blog page and then click the title of the created post. The following error message is shown:

```
Sorry, an error occurred loading the page (500)

/Users/john/repos/keystone-demo/templates/mixins/commenting.jade:33
31| 
32| mixin comment-thread(comments)
> 33| if comments.length
34| for comment in comments
35| +comment-post(comment)
36| 

Cannot read property 'length' of undefined
```

However after changing the code to following gets rid of the error:

```
if comments && comments.length
```

But then the menu bar theme disappears from the post description page, this could be a separate bug altogether.

**Comment by bjwyse** [comment]
My fix for this was to change the argument to the limit method in the query for posts to an integer instead of a string. The relevant line is https://github.com/keystonejs/keystone-demo/blob/master/routes/views/post.js#L34

It is causing an error when rendering the view which prevents other render functions from executing.

**Comment by Nosherwan** [comment]
Thank you @bjwyse your suggestion has worked :)
